<?php

/**
 * Featured Document block
 * Frontend PHP code
 *
 * Uses WordPress' dynamic block method
 * https://developer.wordpress.org/block-editor/tutorials/block-tutorial/creating-dynamic-blocks/
 *
 * @package mojblocks
 *
 */

function render_callback_featured_document_block($attributes, $content)
{

    // Parse attributes found in index.js
	$attribute_box_featuredDocumentID = $attributes['featuredDocumentID'] ?? '';
    $attribute_box_hasDate = $attributes['featuredDocumentHasDate'] ?? 'true';
    $attribute_box_className = $attributes['featuredDocumentClassName'] ?? '';

    // Turn on buffering so we can collect all the html markup below and load it via the return
    // This is an alternative method to using sprintf(). By using buffering you can write your
    // code below as you would in any other PHP file rather then having to use the sprintf() syntax
    ob_start();

    ?>

    <?php
        if (get_post_type($attribute_box_featuredDocumentID) == "document") {
            $featured_doc_details = [
                "title" => get_the_title($attribute_box_featuredDocumentID),
                "date" => get_the_date('d F Y',$attribute_box_featuredDocumentID),
                "link" => get_permalink($attribute_box_featuredDocumentID)
            ];
    ?>
        <div class="<?php _e(esc_html($attribute_box_className)); ?> mojblocks-featured-document">
            <div class="govuk-width-container">
                <?php
                    // Content generated by innerblocks
                    echo $content;
                ?>
                <div class="govuk-grid-row">
                    <div class="mojblocks-featured-document__item">
                        <div class="mojblocks-featured-document__text">
                            <div class="mojblocks-featured-document__headline">
                                <a class="govuk-link govuk-!-font-size-24 govuk-!-font-weight-bold mojblocks-featured-document__headline-link" href="<?php _e(esc_html($featured_doc_details["link"]));?>" >
                                    <?php _e(esc_html($featured_doc_details["title"]));?>
                                </a>
                            </div>
                            <?php
                            if ($attribute_box_hasDate) {
                                $articleDate = strtotime($featured_doc_details["date"]);
                                if (date("Y") == date("Y",$articleDate)) {
                                    $dateString = date("j F",$articleDate);
                                } else {
                                    $dateString = date("j F Y",$articleDate);
                                }
                                $document_array["date"] = $dateString;
                            ?>
                                <div class="govuk-body-s mojblocks-featured-document__date" >
                                    <?php _e(esc_html($document_array["date"]));?>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    <?php
        }

    // Get all the html/content that has been captured in the buffer and output via return
    $output = ob_get_contents();

    // Decode the output in case editors want to add in hyperlinks or other markup
    $output = html_entity_decode($output);

    ob_end_clean();

    return $output;
}
?>
