<?php

/**
 * Banner block
 * Frontend PHP code
 *
 * Uses WordPress' dynamic block method
 * https://developer.wordpress.org/block-editor/tutorials/block-tutorial/creating-dynamic-blocks/
 *
 * @package mojblocks
 *
 */

function render_callback_banner_block($attributes, $content)
{

    // Parse attributes found in index.js
    $attribute_banner_title = $attributes['bannerTitle'] ?? '';
    $attribute_button_link = $attributes['buttonLink'] ?? '';
    $attribute_button_label = $attributes['buttonLabel'] ?? '';

    // Wrapper attributes.
    //
    // get_block_wrapper_attributes() is the PHP counterpart to useBlockProps()
    // in edit(). It emits the generated wp-block-mojblocks-banner class, any
    // custom classes the user set (WordPress persists those in `className`),
    // and anything block supports contribute — so this stays correct as
    // supports are added, without duplicating the logic here.
    //
    // The legacy bannerClassName attribute is deliberately not read: custom
    // classes have always been saved separately in `className`, so nothing is
    // lost for banners saved before the apiVersion 3 upgrade.
    $banner_wrapper_attributes = get_block_wrapper_attributes(['class' => 'mojblocks-banner']);

    // Turn on buffering so we can collect all the html markup below and load it via the return
    // This is an alternative method to using sprintf(). By using buffering you can write your
    // code below as you would in any other PHP file rather then having to use the sprintf() syntax
    ob_start();

    ?>

    <div <?php echo $banner_wrapper_attributes; ?>>
        <div class="govuk-width-container">
            <div class="govuk-grid-row">
                <div class="govuk-grid-column-two-thirds">

					<?php if (empty(trim($content))) { ?>
						<h1 class="mojblocks-banner__title">
						<?php
						 _e(esc_html($attribute_banner_title));
						 ?>
						 </h1>
					<?php
					}
					else { ?>
						<div class="mojblocks-banner__title">
						<?php
							// Content generated by innerblocks
							echo $content;
						?>
						</div>
					<?php
					}
					?>
				</div>
				<div class="govuk-grid-column-one-third">
                    <a href="<?php _e($attribute_button_link); ?>" class="mojblocks-banner__button govuk-button">
                        <?php _e(esc_html($attribute_button_label)); ?>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <?php

    // Get all the html/content that has been captured in the buffer and output via return
    $output = ob_get_contents();
    ob_end_clean();

    return $output;
}
