<?php

/**
 * Featured News block
 * Frontend PHP code
 *
 * Uses WordPress' dynamic block method
 * https://developer.wordpress.org/block-editor/tutorials/block-tutorial/creating-dynamic-blocks/
 *
 * @package mojblocks
 *
 */

function render_callback_featured_news_block($attributes, $content)
{

    // Parse attributes found in index.js
    $attribute_box_featuredID = $attributes['featuredNewsID'] ?? '';
    $attribute_box_hasDate = $attributes['featuredNewsHasDate'] ?? 'true';
    $attribute_box_expiry = $attributes['featuredNewsExpiry'] ?? '';
    $attribute_box_className = $attributes['featuredNewsClassName'] ?? '';

    // Turn on buffering so we can collect all the html markup below and load it via the return
    // This is an alternative method to using sprintf(). By using buffering you can write your
    // code below as you would in any other PHP file rather then having to use the sprintf() syntax
    ob_start();

    ?>

    <?php
        $featureExpires = ($attribute_box_expiry && is_a($attribute_box_expiry, 'DateTime'));

        // The Query
        $args = array(
            'date_query' => array(
                array(
                    'after'    => array(
                        'year'  => date("Y",$expiryDate),
                        'month' => date("m",$expiryDate),
                        'day'   => date("j",$expiryDate),
                    ),
                    'inclusive' => true,
                ),
            ),
            'post_type' => 'news', 
            'posts_per_page' => 5, //only 3 are used, pulling through 5 gives 2 extra in case one is corrupted somehow
        );
        $query = new WP_Query( $args ); 

        // The Loop
        if ( $query->have_posts() ) {
            while ( $query->have_posts() ) {
                $query->the_post();
                
                if (get_the_ID() == $attribute_box_featuredID) {
                    $news_array = [
                        "title" => get_the_title(),
                        "summary" => get_the_excerpt(),
                        "date" => get_the_date('d F Y'),
                        "link" => get_permalink(get_the_ID()),
                        "image" => "",
                    ];
                    break; //found our story, so we don't continue
                }
                
            }
        }
        // Restore original Post Data
        wp_reset_postdata();
    ?>

    <?php
        if ($news_array && count($news_array)) {
    ?>
        <div class="<?php _e(esc_html($attribute_box_className)); ?> mojblocks-featured-news">
            <div class="govuk-width-container">
                <?php
                    // Content generated by innerblocks
                    echo $content;
                ?>
                <div class="govuk-grid-row">
                    <a href="<?php _e(esc_html($news_array["link"]));?>" class="mojblocks-featured-news__item">
                        <div class="govuk-body-l mojblocks-featured-news__headline" >
                            <?php _e(esc_html($news_array["title"]));?>
                        </div>
                        <div class="govuk-body mojblocks-featured-news__summary" >
                            <?php _e(esc_html($news_array["summary"]));?>
                        </div>
                        <?php
                        if ($attribute_box_hasDate) {
                            $articleDate = strtotime($news_array[$i]["date"]);
                            if (date("Y") == date("Y",$articleDate)) {
                                $dateString = date("j F",$articleDate);
                            } else {
                                $dateString = date("j F Y",$articleDate);
                            }
                            $news_array["date"] = $dateString;
                        ?>
                            <div class="mojblocks-featured-news__date" >
                                <?php _e(esc_html($news_array["date"]));?>
                            </div>
                        <?php } ?>
                    </a>
                </div>
            </div>
        </div>

    <?php
        }

    // Get all the html/content that has been captured in the buffer and output via return
    $output = ob_get_contents();

    // Decode the output in case editors want to add in hyperlinks or other markup
    $output = html_entity_decode($output);

    ob_end_clean();

    return $output;
}
