<?php

/**
 * Card block
 * Frontend PHP code
 *
 * Uses WordPress' dynamic block method
 * https://developer.wordpress.org/block-editor/tutorials/block-tutorial/creating-dynamic-blocks/
 *
 * @package mojblocks
 *
 */

function render_callback_card_block($attributes, $content)
{

	// Parse attributes found in index.js
	$attribute_card_image_URL = $attributes['cardImageURL'] ?? '';
	$attribute_card_image_alt = $attributes['cardImageAlt'] ?? '';
	$attribute_card_className = $attributes['className'] ?? '';
	$attribute_card_corner_roundyness = $attributes['cornerRoundyness'] ?? '';
	$attribute_card_excerpt = $attributes['cardExcerpt'] ?? '';
	$attribute_card_image_shape = $attributes['cardImageShape'] ?? 'square';
	$attribute_card_image_position = $attributes['cardImagePosition'] ?? 'top';

	if ($attribute_card_corner_roundyness) {
		$attribute_card_className .= " mojblocks-corner-$attribute_card_corner_roundyness";
	}

	/**
	 * The wrapper class below is built by hand, unlike the other apiVersion 3
	 * blocks in this plugin which use get_block_wrapper_attributes(). That is
	 * deliberate — card has two problems the others do not.
	 *
	 * 1. cornerRoundyness is a custom attribute added by the
	 *    shared-controls/rounded-corners filter, so core knows nothing about it
	 *    and get_block_wrapper_attributes() will not emit mojblocks-corner-*.
	 *    It has to be passed in explicitly via the 'class' key.
	 *
	 * 2. block.json declares supports.align (wide/full), but this callback
	 *    ignores alignment entirely — it reads only className, and alignment is
	 *    stored in a separate `align` attribute. So alignment set in the editor
	 *    is currently NOT rendered on the frontend. Switching to
	 *    get_block_wrapper_attributes() makes core start emitting alignwide and
	 *    alignfull, which means any page where an editor set a card to wide or
	 *    full will change layout on deploy.
	 *
	 * Before making that switch, find out how much content is affected:
	 *
	 *   SELECT COUNT(*) FROM wp_posts
	 *   WHERE post_content LIKE '%wp:mojblocks/card%'
	 *     AND post_content LIKE '%"align"%'
	 *     AND post_status = 'publish';
	 *
	 * Run it per site — this plugin runs on multisite. Then the swap is:
	 *
	 *   echo get_block_wrapper_attributes([
	 *       'class' => trim("mojblocks-card $corner_class"),
	 *   ]);
	 */

	// Turn on buffering so we can collect all the html markup below and load it via the return
	// This is an alternative method to using sprintf(). By using buffering you can write your
	// code below as you would in any other PHP file rather then having to use the sprintf() syntax
	ob_start();

	?>

	<div
		class="wp-block-mojblocks-card <?php _e(esc_html($attribute_card_className)) ; ?> mojblocks-card"
		data-src="<?php _e(esc_url_raw($attribute_card_image_URL)); ?>"
	>
		<?php if (!empty($attribute_card_image_URL)) {  ?>
			<div
				class="mojblocks-card__image mojblocks-card__image-selected mojblocks-card__image--shape-<?php _e(esc_html($attribute_card_image_shape)); ?>"
				style="
					background-image: url(<?php _e(esc_url_raw($attribute_card_image_URL)); ?>);
					background-position: <?php _e(esc_html($attribute_card_image_position)); ?>;
				"
				role="img"
				aria-label="<?php echo $attribute_card_image_alt;?>"
			>
			</div>

		<?php

		}

		// Revert to use old data if content is empty
		if (empty(trim($content))) {

			$attribute_card_title = $attributes['cardTitle'] ?? '';

			echo '<h2>';
			_e(esc_html($attribute_card_title));
			echo '</h2>';

			echo '<p>';
			_e(esc_html($attribute_card_excerpt));
			echo '</p>';

		} else {

			// Content generated by innerblocks
			echo $content;

			// Custom block attributes
			echo '<p>';
			_e(esc_html($attribute_card_excerpt));
			echo '</p>';
		}

		?>

	</div>

	<?php
	// Get all the html/content that has been captured in the buffer and output via return
	$output = ob_get_contents();

	// decode escaped html so users can add markup to content
	$output = html_entity_decode($output);

	ob_end_clean();

	return $output;
}
